spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 5s

      routes:
        - id: service-a
          uri: lb://service-a
          predicates:
            - Path=/service-a/**
          filters:
            -  StripPrefix=1
#          metadata:
#            response-timeout: 4000
#            connect-timeout: 1000

        - id: service-b
          uri: lb://service-b
          predicates:
            - Path=/service-b/**
          filters:
            -  StripPrefix=1

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 3000


logging:
  level:
    ROOT: debug