version: "2"
services:
  nacos:
    image: nacos/nacos-server:2.0.3
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - ./standalone-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
  redis:
    image: redis:6.2.6
    container_name: redis
    ports:
      - 6379:6379
  gateway-demo:
    image: gateway-demo:latest
    container_name: gateway-demo
    ports:
      - 8080:8080
    environment:
      JAVA_OPTS: '-Xms128m -Xmx256m'
    depends_on:
      - nacos
      - redis


